steps:
- task: PythonScript@0
  displayName: 'Download SAClientUtil'
  inputs:
    scriptSource: inline
    script: |
      import urllib.request
      url = 'https://cloud.appscan.com/api/SCX/StaticAnalyzer/SAClientUtil?os=win'
      path = r"$(Build.ArtifactStagingDirectory)/filename.zip"
      urllib.request.urlretrieve(url, path)